### ISSUE TITLE
Invalid Storybook config preset

### ISSUE THREAD

**Issue by zsilbi** [yassilah/nuxt-storybook#1]
Hello!

Thank you for creating this, I tried to set it up but ran into an error immediately.
Storybook throws an error on startup at this line: 

https://github.com/storybookjs/storybook/blob/8f7ed311683a9cabec4390dd572c2f2a253c6d48/code/lib/core-common/src/presets.ts#L24

```bash
 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'name')                                                                                          
  at node_modules/@storybook/core-common/dist/index.js:12:826
  at Array.filter (<anonymous>)
  at filterPresetsConfig (node_modules/@storybook/core-common/dist/index.js:12:757)
  at loadAllPresets (node_modules/@storybook/core-common/dist/index.js:15:1749)
  at buildDevStandalone (node_modules/@storybook/core-server/dist/index.js:33:2265)
```

because preset is `undefined`.

Storybook tries to load and filter the following presets:

**Core** 
```js
[                                          
  'project/node_modules/@storybook/core-server/dist/presets/common-preset.js',
  undefined,
  '@storybook/vue3-vite/preset',
  'project/node_modules/@storybook/core-server/dist/presets/babel-cache-preset.js'
]
```

**Custom** 
```js
[                                                              
  'project/.nuxt/.storybook/main.mjs'
]
```

**Override** 
```js
[] 
```

Steps to reproduce: 

1. `npx nuxi init project`
2. `cd project`
3. `yarn add --dev @yassidev/nuxt-storybook`
4. added the empty storybook config entries and  `@yassidev/nuxt-storybook`  to `nuxt.config.ts`
5. `yarn dev -o`

Using Node v16.16.0 (LTS) - Windows 11 (Ubuntu WSL)

After I modified `filterPresetsConfig` to skip the undefined config preset, it starts without an error, but the following message appears at the canvas:

```
Expected your framework's preset to export a `renderToCanvas` field.

Perhaps it needs to be upgraded for Storybook 6.4?
More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field
```

Many thanks,
zsilbi

**Comment by yassilah** [comment]
Hi ! Oh yeah, it's actually because i've added `@storybook/vue3-vite` to externals so you should just be able to fix that issue by:

```bash
npm install -D @storybook/vue3-vite
```

I'll update the docs, let me know if that works for you

**Comment by zsilbi** [comment]
It works now, thank you!
